name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn lint
      - run: yarn test --ci --reporters=default --reporters=jest-junit

      - name: Generate Jest test report
        if: always()
        uses: IgnusG/jest-report-action@v2.3.3
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - uses: actions/checkout@v2
      - run: yarn install
      - name: Semantic Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
